// sveltekit_frontend/src/lib/main_page/spotifyWidget.svelte
<script lang="ts">
    import apiConfig from "@/api.const.json";
    import { setTrackIsPlaying } from "./spotifyState.svelte";

    import { browser } from "$app/environment";
    import { ArrowUpRight } from "@lucide/svelte";

    const CurrentlyPlayingUrl =
        apiConfig.spotify.baseUrl + apiConfig.spotify.currentlyPlayingUrl;

    const LastPlayedUrl =
        apiConfig.spotify.baseUrl + apiConfig.spotify.lastPlayedUrl;

    interface SpotifyTrack {
        name: string;
        track_url: string;
        album_name: string;
        album_image: string;
        duration_ms: number;
        progress_ms: number;
        is_playing: boolean;
        artists: Array<string>;
        artists_joined: string; // the api doesn't return this, it's for convinience
    }

    async function getCurrentlyPlaying() {
        let request = await fetch(CurrentlyPlayingUrl, {
            mode: "cors",
            headers: {
                "Content-Type": "application/json",
            },
        });

        return request;
    }

    async function getLastPlayed() {
        let request = await fetch(LastPlayedUrl, {
            mode: "cors",
            headers: {
                "Content-Type": "application/json",
            },
        });

        return request;
    }

    /*
        try getting the currently playing track if the response
        status is 204 No Content (actually anything other than 200 OK),
        get last played track 
    */
    async function getSpotifyTrack(): Promise<SpotifyTrack | null> {
        try {
            const currentlyPlayingResponse = await getCurrentlyPlaying();

            if (currentlyPlayingResponse.status == 200) {
                let currentlyPlayingData: SpotifyTrack =
                    await currentlyPlayingResponse.json();

                if (currentlyPlayingData.is_playing) {
                    currentlyPlayingData.artists_joined =
                        currentlyPlayingData.artists.join(", ");

                    // set state for sidebar to use
                    setTrackIsPlaying(true);

                    return currentlyPlayingData;
                }
            }

            const lastPlayedResponse = await getLastPlayed();
            let lastPlayedData: SpotifyTrack = await lastPlayedResponse.json();

            lastPlayedData.artists_joined = lastPlayedData.artists.join(", ");

            if (lastPlayedResponse.ok) {
                setTrackIsPlaying(false);
                return lastPlayedData;
            } else {
                return null;
            }
        } catch (error) {
            console.error("Error fetching track data:", error);
            return null;
        }
    }

    function shortenTextField(text: string, length: number = 20): string {
        if (text.length > length) {
            return text.substring(0, length) + "...";
        } else return text;
    }

    function displayTitle(text: string, length: number = 20): string {
        return text.length > length ? text : "";
    }
</script>

{#snippet skeleton()}
    <div class="flex gap-4 items-center self-start *:animate-pulse">
        <span class="w-32 aspect-square rounded-full bg-base-200"></span>

        <div class="flex flex-col gap-4 items-start justify-center">
            <span class="w-48 h-6 bg-base-200 rounded-lg"></span>
            <span class="w-32 h-4 bg-base-200 rounded-lg"></span>
            <span class="w-42 h-4 bg-base-200 rounded-lg"></span>
        </div>
    </div>
{/snippet}

{#await browser ? getSpotifyTrack() : Promise.resolve()}
    {@render skeleton()}
{:then track}
    {#if track == null}
        {@render skeleton()}
    {:else}
        <div class="flex gap-4 items-center self-start">
            <div class="relative w-32">
                <!-- Blur picture -->
                <img
                    src={track.album_image}
                    class="absolute w-full object-cover aspect-square rounded-full blur-sm opacity-80 z-1"
                    alt=""
                />

                <img
                    src={track.album_image}
                    alt={`${track.album_name} album by ${track.artists_joined}`}
                    title={`${track.album_name} album picture`}
                    class="relative w-full aspect-square object-cover z-2 rounded-full"
                />
            </div>

            <div class="flex flex-col gap-2 font-[Geist]">
                <a
                    href={track.track_url}
                    target="_blank"
                    class="tooltip text-base md:text-lg text-stone-900"
                    data-tip={displayTitle(track.name)}
                >
                    {shortenTextField(track.name)}
                    <ArrowUpRight
                        size="18"
                        color="var(--color-stone-900)"
                        class="inline align-baseline"
                    />
                </a>

                <span
                    class="tooltip text-sm md:text-base text-stone-600"
                    data-tip={displayTitle(track.artists_joined)}
                >
                    {shortenTextField(track.artists_joined)}
                </span>

                <span
                    class="tooltip text-xs md:text-sm text-stone-500"
                    data-tip={displayTitle(track.album_name)}
                >
                    {shortenTextField(track.album_name)}
                </span>
            </div>
        </div>
    {/if}
{/await}

// solidjs_frontend/src/components/spotify-widget.tsx
//@ts-ignore
import apiConfig from "@root/api.const.toml";

import { createResource, Suspense, Switch, Match } from "solid-js";

import { SkeletonRectangle, SkeletonLine } from "@/components/skeleton"

const CurrentlyPlayingUrl: string =
    apiConfig.spotify.baseUrl + apiConfig.spotify.currentlyPlayingUrl;

const LastPlayedUrl: string =
    apiConfig.spotify.baseUrl + apiConfig.spotify.lastPlayedUrl

interface Track {
    name: string,
    track_url: string
    album_name: string
    album_image: string
    duration_ms: number,
    progress_ms: number,
    is_playing: boolean,
    artists: Array<string>,
}

async function getCurrentlyPlaying(): Promise<Response> {
    let request = await fetch(CurrentlyPlayingUrl, {
        mode: "cors",
        headers: {
            "Content-Type": "application/json",
        },
    });

    return request
}

async function getLastPlayed(): Promise<Response> {
    let request = await fetch(LastPlayedUrl, {
        mode: "cors",
        headers: {
            "Content-Type": "application/json"
        },
    });

    return request
}

/*
    try getting the currently playing track if the response
    status is 204 No Content (actually anything other than 200 OK),
    get last played track 
*/
async function getTrack(): Promise<Track | null> {
    try {
        const currentlyPlayingResponse = await getCurrentlyPlaying();

        if (currentlyPlayingResponse.status == 200) {
            const currentlyPlayingData = await currentlyPlayingResponse.json();

            if (currentlyPlayingData.is_playing) {
                return currentlyPlayingData
            }
        }

        const lastPlayedResponse = await getLastPlayed();
        const lastPlayedData = await lastPlayedResponse.json();


        return lastPlayedResponse.ok ? lastPlayedData : null;
    } catch (error) {
        console.error("Error fetching track data:", error);
        return null;
    }
}


function SpotifyWidgetSkeleton() {
    return (
        <div class="w-full h-full gap-4 p-4 flex items-center box-border">
            <SkeletonRectangle classExtra={["w-2/5 aspect-square", "bg-neutral-300"]} />

            <div class="skeleton-lines w-1/2 h-full flex flex-col justify-end gap-4 ">
                <SkeletonLine classExtra={["w-3/5", "h-4", "bg-neutral-300"]} />
                <SkeletonLine />
                <SkeletonLine classExtra={["w-4/5", "h-4", "bg-neutral-300"]} />
            </div>
        </div>
    )
}

export default function SpotifyWidget(props: { classExtra?: Array<string> }) {
    const [trackData] = createResource(getTrack);

    if (!props.classExtra) {
        props.classExtra = []
    }

    return (
        <div class={["spotify-widget flex justify-center items-center w-full h-full bg-neutral-200 rounded-md box-border shadow-md", ...props.classExtra].join(" ")}>
            <Suspense fallback={<SpotifyWidgetSkeleton />}>
                <Switch>
                    <Match when={trackData.loading || !trackData()}>
                        <SpotifyWidgetSkeleton />
                    </Match>

                    <Match when={trackData()}>
                        {(resolvedTrack) => {
                            const track = resolvedTrack();

                            if (!track) return null; // Extra safety check

                            return (
                                <div class="spotify-widget-container w-full h-full p-4 flex gap-4 items-center box-border">
                                    <img src={track.album_image} alt="" class="w-2/5 aspect-square rounded-md" />

                                    <div class="spotify-widget-details h-full flex flex-col justify-end gap-1 text-neutral-900">
                                        <span class="text-sm font-[Inter] text-neutral-500">
                                            {track.is_playing ? "Now playing" : "Last played"}
                                        </span>

                                        <span class="text-xl font-[Inter] font-medium">
                                            {track.name}
                                        </span>

                                        <span class="text-base font-[Inter] text-neutral-600">
                                            {track.artists[0]}
                                        </span>
                                    </div>
                                </div>
                            );
                        }}
                    </Match>
                </Switch>
            </Suspense>
        </div>
    );
}
